### ISSUE TITLE
Dimensions: cm3 -> cm

### ISSUE THREAD

**Issue by Snezhko** [gakarak/BTBDB_ImageAnalysisSubPortal#13]
Единица измерения должна быть cm, а не cm3. Соответствующие значения следует умножить на 100, так как в настоящий момент, похоже, даны значения в метрах, а не сантиметрах

![2018-06-07 20-26-26](https://user-images.githubusercontent.com/26412511/41148305-5a0b000c-6b11-11e8-8deb-8e3b3cb225eb.png)

**Comment by gakarak** [comment]
fix in gakarak@f53dbda1e7ea6078a32daabff438e215f20855e8
